# Include the progress variables for this target.
include progress.make

# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ed/debian/dev/botox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ed/debian/dev/botox

# Default target executed when no arguments are given to make.
default_target: all

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

#=============================================================================
# Special targets provided by cmake.

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ed/debian/dev/botox/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ed/debian/dev/botox/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named cdda2wav

# Build rule for target.
cdda2wav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cdda2wav

# fast build rule for target.
cdda2wav/fast:
	$(MAKE) -f cdda2wav/CMakeFiles/cdda2wav.dir/build.make cdda2wav/CMakeFiles/cdda2wav.dir/build

#=============================================================================
# Target rules for targets named wodim

# Build rule for target.
wodim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wodim

# fast build rule for target.
wodim/fast:
	$(MAKE) -f cdrecord/CMakeFiles/wodim.dir/build.make cdrecord/CMakeFiles/wodim.dir/build

#=============================================================================
# Target rules for targets named deflt

# Build rule for target.
deflt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deflt

# fast build rule for target.
deflt/fast:
	$(MAKE) -f libdeflt/CMakeFiles/deflt.dir/build.make libdeflt/CMakeFiles/deflt.dir/build

#=============================================================================
# Target rules for targets named file

# Build rule for target.
file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file

# fast build rule for target.
file/fast:
	$(MAKE) -f libfile/CMakeFiles/file.dir/build.make libfile/CMakeFiles/file.dir/build

#=============================================================================
# Target rules for targets named hfs_iso

# Build rule for target.
hfs_iso: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hfs_iso

# fast build rule for target.
hfs_iso/fast:
	$(MAKE) -f libhfs_iso/CMakeFiles/hfs_iso.dir/build.make libhfs_iso/CMakeFiles/hfs_iso.dir/build

#=============================================================================
# Target rules for targets named paranoia

# Build rule for target.
paranoia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paranoia

# fast build rule for target.
paranoia/fast:
	$(MAKE) -f libparanoia/CMakeFiles/paranoia.dir/build.make libparanoia/CMakeFiles/paranoia.dir/build

#=============================================================================
# Target rules for targets named scg

# Build rule for target.
scg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scg

# fast build rule for target.
scg/fast:
	$(MAKE) -f libscg/CMakeFiles/scg.dir/build.make libscg/CMakeFiles/scg.dir/build

#=============================================================================
# Target rules for targets named schily

# Build rule for target.
schily: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 schily

# fast build rule for target.
schily/fast:
	$(MAKE) -f libschily/CMakeFiles/schily.dir/build.make libschily/CMakeFiles/schily.dir/build

#=============================================================================
# Target rules for targets named unls

# Build rule for target.
unls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unls

# fast build rule for target.
unls/fast:
	$(MAKE) -f libunls/CMakeFiles/unls.dir/build.make libunls/CMakeFiles/unls.dir/build

#=============================================================================
# Target rules for targets named devdump

# Build rule for target.
devdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 devdump

# fast build rule for target.
devdump/fast:
	$(MAKE) -f mkisofs/CMakeFiles/devdump.dir/build.make mkisofs/CMakeFiles/devdump.dir/build

#=============================================================================
# Target rules for targets named isodebug

# Build rule for target.
isodebug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isodebug

# fast build rule for target.
isodebug/fast:
	$(MAKE) -f mkisofs/CMakeFiles/isodebug.dir/build.make mkisofs/CMakeFiles/isodebug.dir/build

#=============================================================================
# Target rules for targets named isodump

# Build rule for target.
isodump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isodump

# fast build rule for target.
isodump/fast:
	$(MAKE) -f mkisofs/CMakeFiles/isodump.dir/build.make mkisofs/CMakeFiles/isodump.dir/build

#=============================================================================
# Target rules for targets named isoinfo

# Build rule for target.
isoinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isoinfo

# fast build rule for target.
isoinfo/fast:
	$(MAKE) -f mkisofs/CMakeFiles/isoinfo.dir/build.make mkisofs/CMakeFiles/isoinfo.dir/build

#=============================================================================
# Target rules for targets named isovfy

# Build rule for target.
isovfy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isovfy

# fast build rule for target.
isovfy/fast:
	$(MAKE) -f mkisofs/CMakeFiles/isovfy.dir/build.make mkisofs/CMakeFiles/isovfy.dir/build

#=============================================================================
# Target rules for targets named mkisofs

# Build rule for target.
mkisofs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkisofs

# fast build rule for target.
mkisofs/fast:
	$(MAKE) -f mkisofs/CMakeFiles/mkisofs.dir/build.make mkisofs/CMakeFiles/mkisofs.dir/build

#=============================================================================
# Target rules for targets named readcd

# Build rule for target.
readcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readcd

# fast build rule for target.
readcd/fast:
	$(MAKE) -f readcd/CMakeFiles/readcd.dir/build.make readcd/CMakeFiles/readcd.dir/build

#=============================================================================
# Target rules for targets named rscsi

# Build rule for target.
rscsi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rscsi

# fast build rule for target.
rscsi/fast:
	$(MAKE) -f rscsi/CMakeFiles/rscsi.dir/build.make rscsi/CMakeFiles/rscsi.dir/build

#=============================================================================
# Target rules for targets named mkzftree

# Build rule for target.
mkzftree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkzftree

# fast build rule for target.
mkzftree/fast:
	$(MAKE) -f 3rd-party/zisofs_tools/CMakeFiles/mkzftree.dir/build.make 3rd-party/zisofs_tools/CMakeFiles/mkzftree.dir/build

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... cdda2wav"
	@echo "... wodim"
	@echo "... deflt"
	@echo "... file"
	@echo "... hfs_iso"
	@echo "... paranoia"
	@echo "... scg"
	@echo "... schily"
	@echo "... unls"
	@echo "... devdump"
	@echo "... isodebug"
	@echo "... isodump"
	@echo "... isoinfo"
	@echo "... isovfy"
	@echo "... mkisofs"
	@echo "... readcd"
	@echo "... rscsi"
	@echo "... mkzftree"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

