
LIST(APPEND EXTRA_LIBS "schily")

IF(${CMAKE_SYSTEM_NAME} EQUAL "AIX")
   LIST(APPEND EXTRA_LIBS "m")
ENDIF(${CMAKE_SYSTEM_NAME} EQUAL "AIX")



#INCLUDE(CheckIncludeFiles)
#CHECK_INCLUDE_FILES("stdio.h;camlib.h" HAVE_CAMLIB_H)

#TRY_COMPILE(HAVE_LIBC_ISNAN ${CMAKE_BINARY_DIR}  ${CMAKE_CURRENT_SOURCE_DIR}/test_NEED_LIBM.c)
#
#IF(NOT HAVE_LIBC_ISNAN)
#   TARGET_LINK_LIBRARIES(cmTryCompileExec m)
#   TRY_COMPILE(HAVE_LIBC_ISNAN ${CMAKE_BINARY_DIR}  ${CMAKE_CURRENT_SOURCE_DIR}/test_NEED_LIBM.c)
#   IF(HAVE_LIBC_ISNAN)
#   LIST(APPEND EXTRA_LIBS "m")
#   ELSE(HAVE_LIBC_ISNAN)
#      MESSAGE(FATAL_ERROR "isnan function not found anywhere ${CMAKE_SYSTEM_NAME}")
#   ENDIF(HAVE_LIBC_ISNAN)
#ENDIF(NOT HAVE_LIBC_ISNAN)
